//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeRecipes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CakeRecipesDBEntities : DbContext
    {
        public CakeRecipesDBEntities()
            : base("name=CakeRecipesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblIngredient> tblIngredients { get; set; }
        public virtual DbSet<tblIngredientAmount> tblIngredientAmounts { get; set; }
        public virtual DbSet<tblIngredientStorage> tblIngredientStorages { get; set; }
        public virtual DbSet<tblRecipe> tblRecipes { get; set; }
        public virtual DbSet<tblShoppingBasket> tblShoppingBaskets { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<vwIngredientStorage> vwIngredientStorages { get; set; }
        public virtual DbSet<vwRecipe> vwRecipes { get; set; }
        public virtual DbSet<vwShoppingBasket> vwShoppingBaskets { get; set; }
    }
}
