//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeRecipes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRecipe()
        {
            this.tblIngredientAmounts = new HashSet<tblIngredientAmount>();
        }
    
        public int RecipeID { get; set; }
        public string RecipeName { get; set; }
        public string RecipeType { get; set; }
        public int NoPeople { get; set; }
        public string RecipeDescription { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Changed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIngredientAmount> tblIngredientAmounts { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
