//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeRecipes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIngredientStorage
    {
        public int IngredientStorageID { get; set; }
        public int Amount { get; set; }
        public Nullable<int> UserID { get; set; }
        public int IngredientID { get; set; }
        public int Expr1 { get; set; }
        public string IngredientName { get; set; }
        public int Expr2 { get; set; }
        public string FirstLastName { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
    }
}
